### ISSUE TITLE
ValueError: Compression filter "<class 'hdf5plugin.Blosc'>" is unavailable

### ISSUE THREAD

**Issue by cjw296** [silx-kit/hdf5plugin#50]
https://github.com/h5py/h5py/issues/611 suggested this package might be a good way to get the Blosc filter to work, but:

```
$ python3.6 -m venv blosc_example
$ source blosc_example/bin/activate
(blosc_example) $ pip install hdf5plugin
...
Collecting hdf5plugin
  Downloading .../hdf5plugin-2.0.0-py2.py3-none-manylinux1_x86_64.whl (3.8MB)
    100% |████████████████████████████████| 3.8MB 37.5MB/s
...
Installing collected packages: numpy, six, h5py, hdf5plugin
Successfully installed h5py-2.10.0 hdf5plugin-2.0.0 numpy-1.17.3 six-1.13.0
(blosc_example) .$ python
Python 3.6.7 (default, Dec  5 2018, 15:01:38)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py, numpy as np, hdf5plugin
>>> f = h5py.File('test.h5', 'w')
>>> f.create_dataset('data', data=np.arange(100), compression=hdf5plugin.Blosc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/blosc_example/lib64/python3.6/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/tmp/blosc_example/lib64/python3.6/site-packages/h5py/_hl/dataset.py", line 140, in make_new_dset
    maxshape, scaleoffset, external)
  File "/tmp/blosc_example/lib64/python3.6/site-packages/h5py/_hl/filters.py", line 138, in fill_dcpl
    raise ValueError('Compression filter "%s" is unavailable' % compression)
ValueError: Compression filter "<class 'hdf5plugin.Blosc'>" is unavailabl
```

This is IUS Python 3.6 on RHEL7.7. What might be going wrong?

**Comment by vasole** [comment]
@cjw296 

Reading https://github.com/h5py/h5py/issues/1315 I think the syntax you wanted to use is not available in h5py 2.10 and therefore you still have to use the approach suggested in our documentation.

**Comment by kif** [comment]
This is the new way of describing compression options is indeed
something very recent in h5py.

**Comment by t20100** [comment]
The new syntax:
```
f.create_dataset('data', data=numpy.arange(100),
    compression=hdf5plugin.Blosc(cname='blosclz', clevel=9, shuffle=hdf5plugin.Blosc.SHUFFLE))
```
will be working with h5py v3.0 which is not yet out (this is already available from h5py master branch on github).

With h5py v2.x, this is the way to use it is (which should also be compatible with v3.x):
```
f.create_dataset('data', data=numpy.arange(100),
    **hdf5plugin.Blosc(cname='blosclz', clevel=9, shuffle=hdf5plugin.Blosc.SHUFFLE))
```

**Comment by t20100** [comment]
I'm closing it, please reopen if needed.
